---
title: "dss_logo"
author: "Alex Farach"
date: "3/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(randomcoloR)
library(gganimate)
library(transformr)
library(showtext)

# Loading Accenture fonts I found from here: www.whatfontis.com
font_add("rotis", "./rotis-sans-serif.ttf") # old accenture font
font_add("unko", "./unkoi8b.ttf") # new accenture font

# Automatically use showtext to render text for future devices
showtext_auto()

# Tell showtext the resolution of the device, only needed for bitmap graphics.
showtext_opts(dpi = 96)

# Add starting coordinates. These are the xy coordinates for the accenture
# greater than signs
accenture_x <- c(240, 600, 600, 240, 240, 495, 240, 240)
accenture_y <- c(40, 190, 270, 420, 335, 230, 125, 40)
accenture_color <- "purple"
accenture_group <- 1

# create dataframe with initial values in it.
accenture <- data.frame(
  accenture_x, 
  accenture_y,
  accenture_group,
  accenture_color
  )

# this is a loop to populate the original dataframe from above. In it we take 
# take te most recent values and change the x,y coordinates a little bit so that
# the points all move in a circle
for (i in seq(1, 360, by = 0.5)) {
  loop_df <- accenture %>%
    filter(accenture_group == max(accenture_group)) %>%
    mutate(
      accenture_x = accenture_x + cos(i) * 300, #cos(angle)*radius
      accenture_y = accenture_y + sin(i) * 300, #sin(angle)*radius;
      accenture_group = accenture_group + 1,
      accenture_color = randomColor()
    )
  
  accenture <- accenture %>%
    bind_rows(loop_df)
}

# duplicate the dataset 100 times and then create polygon_alpha to add a bunch 
# more polygons with decreasing alpha. This will give a cool effect.
accenture <- accenture %>%
  uncount(100, .id = "frame") %>%
  filter(accenture_group <= frame) %>%
  arrange(frame, accenture_group) %>%
  group_by(
    frame
  ) %>%
  mutate(
    accenture_x_lag = lag(accenture_x), #cos(angle)*radius
    accenture_y_lag = lag(accenture_y), #sin(angle)*radius;
    tail = last(accenture_group) - accenture_group,
    polygon_alpha = pmax(0, (10-tail)/10)
    ) %>%
  ungroup() %>%
  mutate(
    accenture_label_x = mean(accenture_x),
    accenture_label_y = mean(accenture_y)
  )

# Plot the logo.
dss_logo <- 
  accenture %>%
  #filter(accenture_group == 100) %>%
  ggplot(aes(x = accenture_x, y = accenture_y)) +
  geom_polygon(aes(fill = accenture_color, alpha = polygon_alpha)) +
  annotate(
    "text",
    x = unique(accenture$accenture_label_x),
    y = seq(
      unique(accenture$accenture_label_y)+100,
      unique(accenture$accenture_label_y)-100,
      length = 3
      ),
    label = list(
      "Accenture",
      "Federal~Services",
      "Data~Science~Social"
      ),
    family = "unko",
    size = 5,
    color = "#4B636E",
    parse = TRUE
  ) +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.background = element_rect(fill = "#FFFFFF"),
    panel.grid = element_blank(),
    plot.background = element_rect(fill = "#FFFFFF"),
    legend.position = "none"
  ) +
  scale_alpha(range = c(0,1)) +
  guides(alpha = F) +
  coord_equal() +
  transition_manual(frame)

dss_logo
```

